name: r.stonecutter
version: '1.3.0'
main: dev.rudakov.rstonecutter.RStonecutter
api-version: '1.21.1'
description: Расширенные рецепты камнереза с поддержкой дерева, меди, стекла, картин и многого другого.
authors:
  - rudak0v

commands:
  rsc-reload:
    description: Перезагрузить рецепты r.stonecutter
    permission: rstonecutter.reload
    usage: /rsc-reload

permissions:
  rstonecutter.reload:
    description: Позволяет использовать /rsc-reload
    default: op
